SELECT ?subject ?object WHERE {?subject <http://example.org/property/predicate10> ?object . ?subject <http://example.org/property/predicate8> ?object1 . ?object1 <http://example.org/property/predicate5> ?object2} 
